### ISSUE TITLE
Unable to fetch company (Always not found)

### ISSUE THREAD

**Issue by Pietervdw** [IndiciaConnectivity/Indicia.HubSpot#9]
Great job on the library. Thank you!

When I try to get a company using the following code:

```csharp
var company = await _hubSpotApi.GetCompanyApi().ReadAsync("460004600");
```

It does not retrieve the company. I've managed to track the problem down to the fact that it generates the following route for the API request:

```
https://api.hubapi.com/crm/v3/objects/companies/4842546181?hapikey=api-key-here&idProperty=id&archived=false
```
The problem is the **&idProperty=id** parameter. When I remove it, it works fine. 

Am I missing something?

**Comment by Pietervdw** [comment]
I've messed around a bit to see if I can get a way to make this work.

If I add another **ReadAsync** method to the **IHubSpotApiCrudable** interface

```csharp
Task<T> ReadAsync(string id, NoIdReadParameters parameters = null, CancellationToken cancellationToken = default);
```

and create a new **NoIdReadParameters** class :

```csharp
public class NoIdReadParameters: CrudParametersBase,  INotFoundParameters, IQueryParameters
{
    public bool NotFoundReturnsNull { get; set; }
}
```

and then fetch the company like so, it works:

```csharp
var company1 = await _hubSpotApi.GetCompanyApi().ReadAsync(companyId, new NoIdReadParameters());
```

Another option is to add a **ReadByIdAsync** method:

```csharp
Task<T> ReadByIdAsync(string id, bool notFoundReturnsNull, CancellationToken cancellationToken = default);

public async Task<T> ReadByIdAsync(string id, bool notFoundReturnsNull, CancellationToken cancellationToken = default)
{
    var path = GetRoute<T>(id);
    var result = await _client.ExecuteAsync<ObjectApiResult>(path, Method.GET, cancellationToken, null, notFoundReturnsNull);
    return result?.ToHubSpotObject<T>();
}

```

What do you think? Is this a good idea?

**Comment by Confusingboat** [comment]
@Pietervdw I fixed this issue simply by updating the `GetQueryParameters` extension method (located in `Indicia.HubSpot.Core.Parameters`) to skip `idProperty` when its value is `id`, since that's the implicit default.

Before:
```csharp
foreach (var prop in props)
{
    var val = QueryParameterSerializer.Serialize(prop.Value);

    if (!string.IsNullOrEmpty(val))
    {
        queryParameters[prop.Key] = val;
    }
}
```

After:
```csharp
foreach (var prop in props)
{
    var val = QueryParameterSerializer.Serialize(prop.Value);

    if (!string.IsNullOrEmpty(val))
    {
        if (prop.Key == "idProperty" && val == "id") continue;
        queryParameters[prop.Key] = val;
    }
}
```

I haven't tested this outside of the Companies API, but I would assume that you needn't specify `idProperty` at all if it's HubSpot's default, so it should be okay.

Specifying null as the `idProperty` looks like it may also work with no code changes.

**Comment by Pietervdw** [comment]
Thanks @Confusingboat
